const Sequelize = require('sequelize');

module.exports = (
  sequelize,
  { attrName = 'timestamp', suffix = 'Timestamp' } = {},
) => {
  if (!sequelize) {
    throw new Error('The required sequelize instance option is missing');
  }
  sequelize.addHook('beforeDefine', (attributes) => {
    Object.keys(attributes).forEach((attribute) => {
      const key = `${attribute}${suffix}`;
      if (attributes[attribute][attrName] && !attributes[key]) {
        attributes[key] = {
          type: Sequelize.DATE,
          allowNull: false,
          _autoGenerated: true,
        };
      }
    });
  });

  sequelize.addHook('beforeSave', (instance) => {
    const now = Sequelize.Utils.now(sequelize.options.dialect);
    Object.keys(instance._changed).forEach((fieldName) => {
      const fieldDefinition = instance.rawAttributes[fieldName];
      if (instance._changed[fieldName] && fieldDefinition[attrName]) {
        instance.setDataValue(`${fieldName}${suffix}`, now);
      }
    });
  });
};
